@echo off
REM This file generated by AspectJ installer
REM Created on Thu Aug 12 10:50:34 BST 2004 by AndyClement

if "%JAVA_HOME%" == "" set JAVA_HOME=C:\Program Files\Java\j2re1.4.2_01
if "%ASPECTJ_HOME%" == "" set ASPECTJ_HOME=c:\aspectj1.2dev

if exist "%JAVA_HOME%\bin\java.exe" goto haveJava
if exist "%JAVA_HOME%\bin\java.bat" goto haveJava
if exist "%JAVA_HOME%\bin\java" goto haveJava
echo java does not exist as %JAVA_HOME%\bin\java
echo please fix the JAVA_HOME environment variable
:haveJava
"%JAVA_HOME%\bin\java" -classpath "%ASPECTJ_HOME%\lib\aspectjtools.jar" "-Djava.system.class.loader=org.aspectj.weaver.WeavingURLClassLoader" "-Daj.class.path=%ASPECTPATH%;%CLASSPATH%" "-Daj.aspect.path=%ASPECTPATH%" %*
